ALTER TABLE "Project" ALTER COLUMN status DROP DEFAULT;
ALTER TABLE "Project" ALTER COLUMN status TYPE text;
DROP TYPE "ProjectStatus";
CREATE TYPE "ProjectStatus" AS ENUM ('ANALYSE','DEVELOPPEMENT','TESTS','LIVRAISON','MAINTENANCE');
ALTER TABLE "Project" ALTER COLUMN status TYPE "ProjectStatus" USING status::"ProjectStatus";
ALTER TABLE "Project" ALTER COLUMN status SET DEFAULT 'ANALYSE';
